{"filename": "haskell-enclosed-exceptions-1.0.3-233-x86_64.pkg.tar.zst", "name": "haskell-enclosed-exceptions", "base": "haskell-enclosed-exceptions", "version": "1.0.3-233", "desc": "Catching all exceptions from within an enclosed computation", "csize": "17717", "isize": "62403", "md5sum": "f225e547a4e3f2c953dbd76563315f43", "sha256sum": "d816e838b98c0518e9194d5f0a13f91115fa4058e8dfa80da6cb8019cd5e488c", "pgpsig": "iQIzBAABCAAdFiEEtZcfLFwQqaCMYAMPeGxj8zDXy5IFAmSKuzIACgkQeGxj8zDXy5JoCA//YX8KDo9bd0eDVX18Itz8eXbUNECMfd5LIKT/aZXVVqtp83Y3WrVhfPl56AO6RCYEaYmbhfnJvRC4EqfLM3lwAjuFCTrw+xT4VK+pjfrZsiGcubm/gv7F5kQS0JNCkzhjLYdortqwUXdQJQWLF8bB/x4NaVq79HMG7W9sN50pCe5tmJCux0HCTVhpAf5w57cVW3zx+/rTcqdheeX0Kvxiz71zowieZlf/OaIz0vXR9CRZc0lOcTQbRCsjTnyDcSLC3ckJRBN++4G9Whak6A+3MZ5q58kHoRrKEmWRvfNapYAZYbl14XqZMarLsL5fwFX/uyxzkj7CLPc/Lrex8wi7cvepbvneVKtJ7J57VwAkCjLjTroyysGy8F9HPFSElIhI0SUNQzjkEB3Ztn6xk4ApQ2gKmtw2aIChihK1rXTSTE/DXlPm4q6ugrIc22aDurLp1hGAgVoHHhnuffxa9qocZl3mnhbc44zTWvLCyRU8F2e23frXAZo1SwQQ1oub7PuVPViplC3RKLz4iijGcxl2Z/cYk/ONog546XBGsBDDoMCmH6Qm1JwoZ9TL7dk1meN1M5DxP5rbeldo+sMyy5a+KOz0kuQQVUkEyeIdkZGv3y2Md6ouBkqJ+YQi/ltGVJggNPApU2Hezkax7K9jlKXZNRa7bs6cva9OeaPZ1RVkc3s=", "url": "https://github.com/jcristovao/enclosed-exceptions", "license": "MIT", "arch": "x86_64", "builddate": "1686813474", "packager": "Felix Yan <felixonmars@archlinux.org>", "depends": ["ghc-libs", "haskell-lifted-base", "haskell-monad-control", "haskell-transformers-base"], "makedepends": ["ghc"], "tokens": ["haskell-enclosed-exceptions", "haskell-enclosed-exceptions_x86_64", "haskell-enclosed-exceptions_testing", "haskell-enclosed-exceptions_x86_64_testing"]}