{"filename": "haskell-enclosed-exceptions-1.0.3-243-x86_64.pkg.tar.zst", "name": "haskell-enclosed-exceptions", "base": "haskell-enclosed-exceptions", "version": "1.0.3-243", "desc": "Catching all exceptions from within an enclosed computation", "csize": "17716", "isize": "62403", "md5sum": "8cd6279a084d241857277f930aec0b87", "sha256sum": "19970b46981872e73b666f9dadc6de476396ffc78c20cd2e58649d05f729891a", "pgpsig": "iQIzBAABCAAdFiEEtZcfLFwQqaCMYAMPeGxj8zDXy5IFAmVcmXsACgkQeGxj8zDXy5KELhAAsXFKt52VVSsKyXLxA3yWfPFhA6b8Wq/gxlfjuEDqpbb5Wz6hbrpjd1jLROM+2/SlALedo95elqzP6YLUvyB3JFQmgvRU8PIalwC97i9rb3Z+7i64hU7LPCWi2AzLN/kEaHuc62zhBfSzfAszL9G3ce+4VkR7BVYXJwkoBEHA/lmOmD74qYRCoLHSZ6LjirqIULp3e2kblo4yAyHM0884J3wHQYBuTcPYdwWfMw7JfdOXBKt6btdx81D8qVk2V0lNRV1EbYIXo74+ksZ96ZGLy+0kvX7REgVAHkZJgof/1w5E/G7Xr8vKGI1vz8GpTUGa/yK62zrjiJwtOSTFHNktvuMV25yE0XAJ6gjc+BIY9sAtmq0PwJXiuHgaww1ULw3WrrUqnwhSZLm/1SKlkAQi1cwWLENONkTWCnqBPbifWeKRBudvep6/ajMfn4rnL2fB16dpHnFmyyt3hsEVPc30yPCgImGwntTjrWPrQp1x9ojtYrs6YJECfCYiN+rYLPQVZTTBivknBNpVuhw0O1XePw/DwqMsMlkjLYYMRbr7cyQyI1749RupNkXPKElwQ8O41KXt74ybfyvVytDdCt6L0/iouA/sZuiblFaqv0vmixydYmHmi47sdKbMXvLDitc3amqCLXtB3/WFDTknqqug/h96AY41CJ6OdJxI8Cq8n/E=", "url": "https://github.com/jcristovao/enclosed-exceptions", "license": "MIT", "arch": "x86_64", "builddate": "1700567372", "packager": "Felix Yan <felixonmars@archlinux.org>", "depends": ["ghc-libs", "haskell-lifted-base", "haskell-monad-control", "haskell-transformers-base"], "makedepends": ["ghc"], "tokens": ["haskell-enclosed-exceptions", "haskell-enclosed-exceptions_x86_64", "haskell-enclosed-exceptions_testing", "haskell-enclosed-exceptions_x86_64_testing"]}