{"filename": "python-cython-test-exception-raiser-1.0.2-4-aarch64.pkg.tar.xz", "name": "python-cython-test-exception-raiser", "base": "python-cython-test-exception-raiser", "version": "1.0.2-4", "desc": "A trivial extension that just raises an exception", "csize": "11768", "isize": "26817", "md5sum": "097064ea02652a5b5f798b21aaa14e93", "sha256sum": "19d3e48ec1fdae12dc2392b221502a3b3bd2faebd27ed0d0dad4d3999712779a", "pgpsig": "iQIzBAABCAAdFiEEaLNTfzmjE7PldNBndxk/FSvb5qYFAmRWyUAACgkQdxk/FSvb5qaTxA//QlQmHqiPbyQefZhG+JXTWrtGvxiesBwjYHPMIlq8/SBtDo/IL1KCUNTPnK2Yz26msaDT2DcIly413xfiCR8Ifn1fsm8tDZpfwPV6QNiqHx7raKHCKCFV4GjD0roK7BKLRcM9JVRaVV5pmkJFMrp23B0nXH64jnlHtoeWrBc3g1afrFq445Fmj5VV/PXV3ch6/HNZfP9plzrqxK3cgJ1Xi7GCZhH+cEQ5ejL8nlVUoPWQj8tnId5vumwF6D1Sm+z5Jr2hjjVuCY3j7Rl7NsWWRuPsWuHV9UmzEyE+XvhXHeH5SuK8uSqBUiQwJigQTO8aQ4wuxNXzZnzPgC0tP2erIMFhBJ7vkUqwM3ZNxSwAFR8Bjn6FjQRDjYF4TPQLBnF3bCN4h5Iu9dLjavOE2RPkINhDaR5r6B/n3LhZpYOMAiLOAqVPfmmX4Gb1ghQV+uM8qtAKPe6B3fbi146qjszXzgWyNnS0eVDSMoRvCJ5DJfBplfjO7wjze+bQyW8X+aniJvlEu0zWDO/AIxPSIDzH5gLKk7xM3lgcUzR9wfGEui1+WgShw4l1nisnqxy5xRxzuQ+3tefTj3mhq/kawquzbq6nYUWsSmFQbsh2G+5CfKc2yzngLE+QxlVezLAbMqUAr5lf7nEcAPEKWVW89FAMpWiwoyRsZDG+3hPI7mcfYUY=", "url": "https://github.com/twisted/cython-test-exception-raiser", "license": "MIT", "arch": "aarch64", "builddate": "1683409200", "packager": "Arch Linux ARM Build System <builder+n1@archlinuxarm.org>", "depends": ["python"], "makedepends": ["python-setuptools", "cython"], "tokens": ["python-cython-test-exception-raiser", "python-cython-test-exception-raiser_aarch64", "python-cython-test-exception-raiser_unstable", "python-cython-test-exception-raiser_aarch64_unstable"]}