{"filename": "certbot-dns-nsone-2.8.0-1-any.pkg.tar.zst", "name": "certbot-dns-nsone", "base": "certbot-dns-nsone", "version": "2.8.0-1", "desc": "NS1 DNS Authenticator plugin for Certbot", "csize": "14923", "isize": "41221", "md5sum": "d4a9172ba0008688c76a42fa977076bc", "sha256sum": "df6e5344629903698b3c16dda4f0aa3eded324902a0a3258098a3877906bc28b", "pgpsig": "iHUEABYKAB0WIQTnXNSBSnetlDx6taPglZ/qi1UFOQUCZZ3YBwAKCRDglZ/qi1UFOXMBAQCkam0pgMsZ0gj6O8E6+uHNMI0i7xP/a3hXIjFb7bgC1QD9Eg8sXwUigKdoCkud7tYj5L7svxhBjRu3lhahgE2j8AE=", "url": "https://pypi.python.org/pypi/certbot-dns-nsone", "license": "Apache", "arch": "any", "builddate": "1704843253", "packager": "George Rawlinson <grawlinson@archlinux.org>", "depends": ["certbot=2.8.0", "python-acme=2.8.0", "dns-lexicon"], "makedepends": ["git", "python-build", "python-wheel", "python-installer"], "checkdepends": ["python-pytest"], "tokens": ["certbot-dns-nsone", "certbot-dns-nsone_x86_64", "certbot-dns-nsone_unstable", "certbot-dns-nsone_x86_64_unstable"]}