{"filename": "haskell-enclosed-exceptions-1.0.3-232-x86_64.pkg.tar.zst", "name": "haskell-enclosed-exceptions", "base": "haskell-enclosed-exceptions", "version": "1.0.3-232", "desc": "Catching all exceptions from within an enclosed computation", "csize": "17687", "isize": "62401", "md5sum": "c4edf409e9db8d4bb7241ae5baf51544", "sha256sum": "7edacec126acadb60f3806dd2cc9c04fee1f1dc02074016a8d32d9e4f9e72e0a", "pgpsig": "iQIzBAABCAAdFiEEtZcfLFwQqaCMYAMPeGxj8zDXy5IFAmR8xrUACgkQeGxj8zDXy5JgJxAAhdDhPNdtlC63eM0dt+KhkvG1wK2LAY6BMuyqeI5Wn1XZBKlxDKTcWzntH3I5075HwQYo9HhZC2e3X1CgzRxnllCaM/SUzfzCdABD7DaCBnYnhcRtHtEjCf3B21D9nnNTazKpxo1G8i9hBSYA1Qp1vmJ9nsNAgaIXEPdWJ4cSSQ4Gs2+UAQbuL8iQZ/Kn9Nr6LgCvkA1TRc4P5eGkpGA9I8CAH9UNv2d+RSGCsqgwvI5OAJyD1adVSwMw8KXD5RpMJZVyL+3BeIZULxmH1kAxNMlFXLBVeWtpuu5entU0HSVSAp08DU7xlddSWcEN2LlnLw7HbT4k6ISzRzIGLRjRcr82YeJo0gvEhTenTkA2CR6T+N/drMahM9aTpfN9KIkMNjrfu4BrIGlRdwK9dXpELEex4SrvUjURQHa74NkB0soBSL1u6/9vDh0KExPqT1mm4z/nJHefKKRKrxZyzkK5Iqg3W1a7TPbzxhAx5/3le/kbbOjz048QHx8d9Q2zsZRcqUkAv7BdhFgC0Z08UqRD/ndC2NZDGMTKsNJThPrHwiZSAMhLfPMvwuu7Ont06wy1vrANV+ZTRHtj0w3/Be+DtIU5KsHLKALl40IQ0ln8NWKP/oIKbnAsi1aLIKKAyx2odGuvxS5q/DFdI/JL1i9lU7XSZUdwOK6gE01W9A8R9H8=", "url": "https://github.com/jcristovao/enclosed-exceptions", "license": "MIT", "arch": "x86_64", "builddate": "1685898910", "packager": "Felix Yan <felixonmars@archlinux.org>", "depends": ["ghc-libs", "haskell-lifted-base", "haskell-monad-control", "haskell-transformers-base"], "makedepends": ["ghc"], "tokens": ["haskell-enclosed-exceptions", "haskell-enclosed-exceptions_x86_64", "haskell-enclosed-exceptions_unstable", "haskell-enclosed-exceptions_x86_64_unstable"]}