{"filename": "haskell-enclosed-exceptions-1.0.3-236-x86_64.pkg.tar.zst", "name": "haskell-enclosed-exceptions", "base": "haskell-enclosed-exceptions", "version": "1.0.3-236", "desc": "Catching all exceptions from within an enclosed computation", "csize": "17736", "isize": "62410", "md5sum": "2f2629ccb2ea1ee3bb089f7c7a6e5857", "sha256sum": "43a30c4b614ec9bcfa35cd6056f32ec9a3b0c228c2f96eb123de77790951ef54", "pgpsig": "iQIzBAABCAAdFiEEtZcfLFwQqaCMYAMPeGxj8zDXy5IFAmUMdpUACgkQeGxj8zDXy5JXvA/9FbvPGbP6WeXtAB+fZvAdQmh/8nOPHt7kmyb6Qmn0FPvKYDve1wR3nbP1Y3NN39BL4ziA/8vzKZmN+dv2iwRt5LX8XI7z24MxJKThl25hcDv7U9W/eLq88wPrP3wntfi8Qxf5xVGldl3ALPqnQwfrlqCXZUxO8O/J8Id/9WtIAx4AqKBIZxlr4OZ0Amo2xrEb8r4LNYc5yo0Nlzr8EPJS3W3+aNJpghuosqj1ZhuMefbNeSuT5o41p9nYzrh6+2J8j8nFkb40fic5BtGD8ODekN0S4W8aNAa/ck9jLvNs9sSIgOgImXWi0oGSD0m2qIU5AFmh+rjWH7IfkeyNZSMOxPaP8GgAySKoZaYWMDNlDV86GfbNvvnWIgZcmm6NyzN/BpEvDJysyy9Dyovn4+LjvTDt9Nx+vr5LkqnmUO10on0qTlE9jt/1Qi6T4N3m6o/U09+Je2vVS1woznM8GxkmkpAvkjFdp7aOZdHzv0La3oyi7yiqJpd/sykPNXlheHclR/W+GZh9MHIdAQ4WvPlwkM62medP1n5OtLgXbLCYlLq3ilq7G5So3ZOo86sfEE1OF+kCxdDADgkScIAYBGp+Jf+g2TEjuZaVu+ZE1i47dK8poptFz2KB99nrPqSmHLY2ltarHpIRFgiRtYX4FWp58ZMADtABeYOcZg5kzYwqhxw=", "url": "https://github.com/jcristovao/enclosed-exceptions", "license": "MIT", "arch": "x86_64", "builddate": "1695315580", "packager": "Felix Yan <felixonmars@archlinux.org>", "depends": ["ghc-libs", "haskell-lifted-base", "haskell-monad-control", "haskell-transformers-base"], "makedepends": ["ghc"], "tokens": ["haskell-enclosed-exceptions", "haskell-enclosed-exceptions_x86_64", "haskell-enclosed-exceptions_unstable", "haskell-enclosed-exceptions_x86_64_unstable"]}