{"filename": "haskell-enclosed-exceptions-1.0.3-338-x86_64.pkg.tar.zst", "name": "haskell-enclosed-exceptions", "base": "haskell-enclosed-exceptions", "version": "1.0.3-338", "desc": "Catching all exceptions from within an enclosed computation", "csize": "13512", "isize": "40190", "md5sum": "b838ee54edc1b4ef36d2d51637ae586f", "sha256sum": "b9f35418dc35e0cf7b67540278d44090c44e13753b2c646113fb240a4e6d6d98", "pgpsig": "iQIzBAABCgAdFiEEtZcfLFwQqaCMYAMPeGxj8zDXy5IFAmjUY48ACgkQeGxj8zDXy5KAGA/5AT8tgGvcDzF+h8F9VNcGrY0+ukioK8dbDrO9thSv78A8yHCJr1+JvM33BvBQjCcGhzn8u143Ry8e+EquOMKQ4K17jMcg0OMRL+YRy4PB2KFA08AxCN7InsMtsHn3uPJcQM+zMpqaKXYtlTQ5KUiyaWtwoCKHxxnpgNcMaViwTXfzxwtNpeVd9bs8Fi8P+jhiiXNYDMkKLJsE9NKSuXdzrIbqu57bB7cJFpnMgQho6n7t1TU7Xa14YJ7iob7hqHDFsXGypV3KOur5GMR034+WcmPP5Hw/m7oRzqvU1v1BfvxKu+iDmPxzjxOma4FQkb18ttS/Kjv/D3ZJQtl3jvID/yPK4sZWQXsmyEjjta6QaBBsRfTHpCfUQPcz+LbqKvbPnqjDg8wgMut5yyykWyPw8ms8sKPrmqIubzRmY68BRLTPPxijNma6ACvtQn3bVsoO8Sx6BYPCTAWIA8ZX9Wmk2t8hvGxE7TFMuRxtMd9Q+wdsr/ltM8Giua8qTLFHjPv/9AFT8zDRZrW3JHCyg8dIV+LZgMXVT3fWL9Rwc14NYyxPAYmxCeXgs3A0Kz9KoeRAvXswxnNo3YBtaoxCKHqthic4Rv/H7lBbjnR113WwL+rMBqM5scUBoROGicGtABds6/icemgNgmrDfqEBTOMTKi3IwpZxMONN59jf7JofJw8=", "url": "https://github.com/jcristovao/enclosed-exceptions", "license": "MIT", "arch": "x86_64", "builddate": "1758749564", "packager": "Felix Yan <felixonmars@archlinux.org>", "depends": ["ghc-libs", "haskell-lifted-base", "haskell-monad-control", "haskell-transformers-base"], "makedepends": ["ghc"]}