{"filename": "haskell-enclosed-exceptions-1.0.3-296-x86_64.pkg.tar.zst", "name": "haskell-enclosed-exceptions", "base": "haskell-enclosed-exceptions", "version": "1.0.3-296", "desc": "Catching all exceptions from within an enclosed computation", "csize": "13523", "isize": "40186", "md5sum": "3cdb26c408161dd858cdb1a22ea2d2e1", "sha256sum": "2b3d6febb61dda9e0b83af5dd9c0fba8d932054dba07b2b051a2246538336042", "pgpsig": "iQIzBAABCgAdFiEEtZcfLFwQqaCMYAMPeGxj8zDXy5IFAmiiAYsACgkQeGxj8zDXy5Lh/BAAqitrhmMe4iEVv8l4kDl5yG/YaxFzxQhhJCas9xMCDYOwXCikXhn97vv8+Q/YNvMZxMmlRo7lN655lXumYqoHnTs6KBrKOJfpDZt6x9EOSX1B+0RCFlbDZJ7BjfIyPH1kQZzgFyJBPdQFJsFq2GqT4PMB1ieIeeDNDNS2Q3s9EQKwrhdIobzJ5mTs+FkdOVtn7gh0bsnZLpucVMY4J384R6qhUIlakIEbj0CpqVpKT8KymMdRp96+1o9rje2apwuHbDu4RryA2g/eXNX4WirJXj2PVX+NeFGed0W1WDJr/3huRNWiLJbjU3P8JSG48X97M9d5HlQ7OLygHu4WJaZkiXOHQbWuE0P52S0n6H5s5fP9nU9WfN5VNqN73lrT5AwOaM1LhiAdC6MBrUeNXcI9P4PZImYCNXzn26/PQYnVfM/ArIOWxLq+lfMy3sifFwo/FCnHQDnMTg8lsfHuh9TPo6yd/xKnKG6bhE74C/lwmF/dMB/7hGcSsUUjyUd+2u01xQYXQ8GjvxqXv5jhFqFpXE+DSLCpFEtT6pyDDenmdhOYkx4fyVt1qoPYzKzmhB+vzcir7HHi5DeiVF4Pu2g6PgdzgeYJszXzf3oOBKB5n0GeEwf3oZUmFLraROltJJhdnd0drtX30pWWXr0sU6ZW6rNpUqVN6W9nrh4uCiQKcEs=", "url": "https://github.com/jcristovao/enclosed-exceptions", "license": "MIT", "arch": "x86_64", "builddate": "1755447663", "packager": "Felix Yan <felixonmars@archlinux.org>", "depends": ["ghc-libs", "haskell-lifted-base", "haskell-monad-control", "haskell-transformers-base"], "makedepends": ["ghc"]}