{"filename": "fail2ban-1.0.2-4-any.pkg.tar.zst", "name": "fail2ban", "base": "fail2ban", "version": "1.0.2-4", "desc": "Bans IPs after too many failed authentication attempts", "csize": "865143", "isize": "5203522", "md5sum": "8488bf568548f6e270172a09d5c473fb", "sha256sum": "8287fa42cac4e74b650bb72c1946a2e28a9a986d9ae3c808e0c5e5a6c8a7b362", "pgpsig": "iQIzBAABCgAdFiEEBNw/sURf7KgTwn766k97MhqQatkFAmRpIzUACgkQ6k97MhqQatnGkA//XD9m3+7SftSbcIc0riMA5HtSUpYCQH0y5d43WKPMZSRh+pCbYH0aVOjmeMAuBDonYc35GK6baSUVFo54FeUyuxOTQ+1Lw0jCCtT91d0dPUNRpuHyLyDQcpc/ps1QJAYJJjkEXBKTFtvbv2oC+Hnd75xR91GI0ogZ7xdAfm0Lgu+aTFkLX0HPFZwX0BXXXgYnddeNEUG4rreIcjEYZmi2QvmM3C6JE7xmlcccCfvQvqIW0BHxxAE9z51g8fWg+IBaAjvKPb6tFZcvjOMMlCEt4DWwOCD3rID8yUpZmosox7bJMnW/6fp+tLySfbBnooYFu/tnGjf6BmZ1SzIuFFYB012G/koORABRam3LEw15E2wTz1l1kpbcgRh1TLDoJ43PxwncZqX7uvYauMGlymvw+WZnv45g3OauxUJx0wi2xg9nxxEPYTIbqczZWFQDBl0TEUsR08P+r/qOzoAM0UJB+hM9gXmiC2Jb02/bw8tXGUgKEw4PyQR5ZfwHpjis2enREISqQnZYW33oUZrUYYo/FjqNBM1HydZG8V6djjutDZ1E2fYbiirh45R6eoLzqXEn3bf20Xmc2geRTO3ea4p/SzeiJnOVB/OAKFNqVaq0lR3RQ+3EmiCFliSInSI2KOWfaZh9ldwFtghj0RXgGr5H20NBW5TlieIUwRtQzwlB+jc=", "url": "https://www.fail2ban.org/", "license": "GPL", "arch": "any", "builddate": "1684611489", "packager": "Daniel M. Capella <polyzen@archlinux.org>", "depends": ["python-pyinotify", "whois", "sqlite", "python-systemd"], "optdepends": ["ipset: for a firewall backend", "firewalld: for a firewall backend", "iptables: for a firewall backend", "nftables: for a firewall backend"], "makedepends": ["python-setuptools"]}