{"filename": "haskell-enclosed-exceptions-1.0.3-284-x86_64.pkg.tar.zst", "name": "haskell-enclosed-exceptions", "base": "haskell-enclosed-exceptions", "version": "1.0.3-284", "desc": "Catching all exceptions from within an enclosed computation", "csize": "13544", "isize": "40187", "md5sum": "4099dfce2942f89ca7f381a37d02cb9a", "sha256sum": "3897e6a234064990ff2fc2ded9fa2d1f40aebae026c5e574272950317a502000", "pgpsig": "iQIzBAABCgAdFiEEtZcfLFwQqaCMYAMPeGxj8zDXy5IFAmhKPDkACgkQeGxj8zDXy5JxVxAAkAuZgTEVWXgbwR3FwHoAPvKvdwDWEE5v4un/7n5S3OCvJtf0xrOnDfAOXTPuw/T4IN0PTARG+zbWZjNPHHl4V6wPZJn7hCY4OU8c+fPo2DoCaNigKe5YK08l2F7gPLFoW2d0tV9M5X4IzWMwOL/o5X6zvmz+AwKC4pJ/TQPxdCXucfivnMzbfrgSqlCHvLMQS3gsJmIofp2unwcRK8LoB2/pMAbLSXxR9zlvnSYBn6X6HQsFWnYoe/1CcXqFBZLFgZpBJUfZCaogVzTOrU1YL6DwCT0qmtzLv7Mjr3Ac+8gjGRbjbszQzI6HMlEY59kSM/WKpHEKbU2jgWJNES40jJ+VeuG8bcLkqvTiIMCtXUl0uyEKzCnRXmvJDMAqMwf1B6Qe9iNxiigyEHkx5Do9l+ZlTj23LMzzINLie5UlbuQb+bUrOXf5TH4uSeOB9X4DbKYl5bltqj69mdxjJAwbbZ8nu4cQcuZIDKiGNDKHDPbTNKaNnDWkxh1Ywg3uxN11B+uoaA+22DN1GeMxy1q1nIYQQ0lIZS06TrV9y/tpMn9dPDSIGHDBZK+BAqOTBm0rggjvHO1/odVfgOyrlPhaYnsYj6v+wqTwgX/xJ0JAJ1I5ejPhlN1xwu3xr1dL27H87c9Bg0w03nWBzCX5dPhgxMe+O84BCrdahG+qOf0XhWg=", "url": "https://github.com/jcristovao/enclosed-exceptions", "license": "MIT", "arch": "x86_64", "builddate": "1749695523", "packager": "Felix Yan <felixonmars@archlinux.org>", "depends": ["ghc-libs", "haskell-lifted-base", "haskell-monad-control", "haskell-transformers-base"], "makedepends": ["ghc"]}