{"filename": "haskell-enclosed-exceptions-1.0.3-251-x86_64.pkg.tar.zst", "name": "haskell-enclosed-exceptions", "base": "haskell-enclosed-exceptions", "version": "1.0.3-251", "desc": "Catching all exceptions from within an enclosed computation", "csize": "13500", "isize": "41249", "md5sum": "fb4ce72e74c474c9d0098d3bb1867140", "sha256sum": "f1aa0cf8f3d8e7898b7a4d7d01166df42ac08f34f8ae559e92e9e50ed53f1c46", "pgpsig": "iQIzBAABCAAdFiEEtZcfLFwQqaCMYAMPeGxj8zDXy5IFAmXeFYMACgkQeGxj8zDXy5KD/Q//SCggA9opwmonTHExqmPBAImClihSomcDbRqHgAHDc7zFcvrjn3v1ipXFpVNaYDlJ+XnvJh1l3NCIQDYRIRCLkTFLYx/lTS4BKRaRkjKceOOfS/JRIPT48hLb9iNXzVKHyM42199Pl5hjvhsarYI4qXX4ReZtHZfXCPr3N8/WOW2/TN6xuS7apo5W3aYNBNnOMwhqQDWtgMUFNpvC1HrRO36+fMjV8DcCZNjXpM4mHlkXKBqGQVo/P3cLIkyeWGn7S8pnxswHRC6jtMPKpnNi3DmFQW0NfDLxLigjtwXisWqUpvUN7RposrP7UH1hpM+hZvRo3hEjQrG3U22ruOoGWiMGC4IwUk2J3dAVv4AvHyn07Xck4QSBfbXQ2fOodFGOvQA8S9/64nof1tZBEKqR+RWqeir5DtqhysMMkkQubIu8ZZRLwwCIV1uZR3OVWO79LY3lOFQhspnQCcLuP6F8+9J6gHLc/CwAfxfAIjIcQhyrWK7aDWXZcNCUc0SrCwe+NmyJrI9MyuWFdN9O1NmTd4n6DmJpBG5QSQxM5nBIIIe7XUq6/65omR0PuGCViJzEsf71w2j5c8kp1hsSd9RbNmlTtH3ebekTbmHbspcBMENJozELZco8f4d0jZV4LHuTrIcYP/pBop45oqEnqvGzen5fLBgqi/I+qymSfFrHokM=", "url": "https://github.com/jcristovao/enclosed-exceptions", "license": "MIT", "arch": "x86_64", "builddate": "1709053297", "packager": "Felix Yan <felixonmars@archlinux.org>", "depends": ["ghc-libs", "haskell-lifted-base", "haskell-monad-control", "haskell-transformers-base"], "makedepends": ["ghc"], "tokens": ["haskell-enclosed-exceptions", "haskell-enclosed-exceptions_x86_64", "haskell-enclosed-exceptions_stable", "haskell-enclosed-exceptions_x86_64_stable"]}