{"filename": "llvm-16.0.6-1-x86_64.pkg.tar.zst", "name": "llvm", "base": "llvm", "version": "16.0.6-1", "desc": "Compiler infrastructure", "csize": "18735240", "isize": "106985837", "md5sum": "dceed6da2f9ff6131a3a89f57be8dda2", "sha256sum": "10552e1a43253a4dc17d5b60bf41f700bc3e62cd99b3e2da3865a25300b81f82", "pgpsig": "iQEzBAABCAAdFiEEhs/8qRjPOvRxR1iAUeixSKmZnDQFAmTfjB0ACgkQUeixSKmZnDQEiwgAgRyg1mZEoidUxvUgN3vJ36VAMpRHtjLD8ZrItR7W9VCmjuAtzYfQFRA1b5jbz5VvZ3qfud5lTi8qyh6zP9edJ+auVlq79uOxL6XhSE0jg64+Rp94mwwaEh6W2WQVHZ9gaq2PePpQfIAHGPCkLhSscZEG6aFodW6NDFHoH+Wc6Z5GdvVyokLVa/7djwt83kIhaQDghMFzuVGIOqh7f2gVaZrD7tGDlWO0WiALzvgH2grfnuF3q0+ruQIYv+NWPLEWrvlvZvPXaOh6juIptw4LWcUePrQV/5I45M07ftkrFadM9rAU7AP1lE2jpX7MwjqEn8C28N9KkCZD5NS8JUogrg==", "url": "https://llvm.org/", "license": "custom:Apache 2.0 with LLVM Exception", "arch": "x86_64", "builddate": "1692370890", "packager": "Evangelos Foutras <foutrelis@archlinux.org>", "depends": ["llvm-libs", "perl"], "makedepends": ["cmake", "ninja", "zlib", "zstd", "libffi", "libedit", "ncurses", "libxml2", "python-setuptools", "python-psutil", "python-sphinx", "python-recommonmark"]}